// Code generated by scripts/package-engine.sh. DO NOT EDIT.

//go:build darwin && arm64

package engine

// Values describing the payload in data/, taken from the chdb-core release it
// was built from.
const (
	// Version is the chdb-core release this engine came from.
	Version = "v26.7.3"
	// FileName is the name the library must be written under.
	FileName = "libchdb.so"
	// Digest is the SHA-256 prefix of the extracted library. It names the
	// extraction directory, so equal digests mean identical bytes.
	Digest = "109811f89d8fff7a22f8d7293827e4ec"
	// Size is the extracted size in bytes.
	Size = 341977376
)
