// Code generated by scripts/package-engine.sh. DO NOT EDIT.

//go:build darwin && amd64

package engine

// Placeholder values. scripts/package-engine.sh overwrites this file with the
// metadata of a real chdb-core release; an empty Version means this revision
// carries no engine.
const (
	// Version is the chdb-core release this engine came from.
	Version = ""
	// FileName is the name the library must be written under.
	FileName = "libchdb.so"
	// Digest is the SHA-256 prefix of the extracted library. It names the
	// extraction directory, so equal digests mean identical bytes.
	Digest = ""
	// Size is the extracted size in bytes.
	Size = 0
)
