name: chDB-go Release

on:
  release:
    types: [created]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch library
      run: |
          make install
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Build
      run: |
          go mod tidy
          make build 
    - name: Test
      run: ./chdb-go "SELECT 12345"
    - name: Get Version
      run: |
        echo "VERSION=${{  github.ref_name }}" >> $GITHUB_ENV
    - name: Upload chdb-go and libchdb.so to release
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        cp -a /usr/local/lib/libchdb.so .
        tar -czvf linux-x86_64-chdb-go.tar.gz libchdb.so chdb-go
        gh release upload ${{ github.ref_name }} linux-x86_64-chdb-go.tar.gz --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION }}

  build_mac:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Fetch library
      run: |
          make install
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Build
      run: |
          go mod tidy
          make build
    - name: Test
      run: ./chdb-go "SELECT 12345"
    - name: Get Version
      run: |
        echo "VERSION=${{  github.ref_name }}" >> $GITHUB_ENV
    - name: Upload chdb-go and libchdb.so to release
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        cp -a /usr/local/lib/libchdb.so .
        tar -czvf macos-x86_64-chdb-go.tar.gz libchdb.so chdb-go
        gh release upload ${{ github.ref_name }} macos-x86_64-chdb-go.tar.gz --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION }}
