name: chDB-go Release

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch library
      run: |
          make install
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
    - name: Build
      run: |
          go mod tidy
          make build 
    - name: Test
      run: ./chdb-go "SELECT 12345"
    - name: Get Version
      run: |
        echo "VERSION=${{  github.ref_name }}" >> $GITHUB_ENV
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            chdb-go-linux
        tag_name: ${{ env.VERSION }}
        release_name: chdbgo_${{ env.VERSION }}
        draft: false
        prerelease: false
        overwrite: true   
