// Code generated by scripts/package-engine.sh. DO NOT EDIT.

//go:build linux && arm64

package engine

// Values describing the payload in data/, taken from the chdb-core release it
// was built from.
const (
	// Version is the chdb-core release this engine came from.
	Version = "v26.7.3"
	// FileName is the name the library must be written under.
	FileName = "libchdb.so"
	// Digest is the SHA-256 prefix of the extracted library. It names the
	// extraction directory, so equal digests mean identical bytes.
	Digest = "406ee06d7ff17e01bd565feccec4ce15"
	// Size is the extracted size in bytes.
	Size = 496509312
)
