// Code generated by scripts/package-engine.sh. DO NOT EDIT.

//go:build linux && arm64

package engine

// Values describing the payload in data/, taken from the chdb-core release it
// was built from.
const (
	// Version is the chdb-core release this engine came from.
	Version = "v26.7.0"
	// FileName is the name the library must be written under.
	FileName = "libchdb.so"
	// Digest is the SHA-256 prefix of the extracted library. It names the
	// extraction directory, so equal digests mean identical bytes.
	Digest = "4ecc2863c65d78e5c23be15be8332423"
	// Size is the extracted size in bytes.
	Size = 452070144
)
